### ISSUE TITLE
Make svg images scale with font changes

### ISSUE THREAD

**Issue by seanfarley** [elken/exercism-modern#10]
While the emojis scale with the font, the svg images, do not:

<img width="1354" alt="Screen Shot 2022-10-06 at 7 46 38 PM" src="https://user-images.githubusercontent.com/20887/194587774-015d6a94-940e-42b4-9f89-2232528ad6b7.png">

**Comment by elken** [comment]
Thanks, this should be an easy one; I'm setting the width to be a fixed number.

So I just have to find a nice formula to make it scale based on the current font size (approximately, I'm not bothered about making it pixel-perfect for every single font)
