### ISSUE TITLE
tablist dependency / Spacemacs

### ISSUE THREAD

**Issue by gregorybleiker** [elken/exercism-modern#12]
Hi there

I struggling installing the package on spacemacs. I had to add `tablist` as a dependency, resulting in:

```
dotspacemacs-additional-packages '(tablist (exercism-modern :location local))

...

(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (require 'tablist)
  (require 'exercism-modern)
  )


``` 
in `~/.spacemacs`. 
I also set `exercism-modern-config-file` in the custom-set-variables to the correct location. However, a lot of things still seem to be missing (for instance if I M-x exercism-modern-view-tracks, nothing happens...) 

Do you have any guidance for a setup in spacemacs?

**Comment by elken** [comment]
I don't use spacemacs so I can't tell you what to do there. I've tested it with vanilla Emacs and it works fine, so I'd say ask around whatever help channels they have to offer as it seems to be an issue with them.
